# Generated by Django 5.2 on 2025-04-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "rollno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=20)),
                ("phonenumber", models.CharField(max_length=15)),
            ],
            options={
                "db_table": "students",
                "managed": False,
            },
        ),
    ]
