# Generated by Django 5.2 on 2025-05-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="jnr_core",
            fields=[
                (
                    "rno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=10)),
                ("section", models.CharField(max_length=5)),
                ("subject1", models.IntegerField()),
                ("subject2", models.IntegerField()),
                ("subject3", models.IntegerField()),
                ("phone", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="snr_core",
            fields=[
                (
                    "rno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=10)),
                ("section", models.CharField(max_length=5)),
                ("subject1", models.IntegerField()),
                ("subject2", models.IntegerField()),
                ("subject3", models.IntegerField()),
                ("phone", models.CharField(max_length=15)),
            ],
        ),
    ]
